version: "3.8"
services:
  web:
    image: node:lts-alpine
    command: >
      sh -c "
        npm install &&
        npm run dev
      "
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 5173:5173
    user: 1000:1000
